### ISSUE TITLE
hyp_dateFromISO8601String: Not converting to millisecond precision

### ISSUE THREAD

**Issue by bonebox** [hyperoslo/NSManagedObject-HYPPropertyMapper#103]
For example, when using Sync to map the string `2016-05-06T19:04:19.911Z` to NSDate, then using NSDateFormatter.stringFromDate to convert back to a string, I get `2016-05-06T19:04:19.000Z`.

**Comment by 3lvis** [comment]
Damn, this should be straightforward though. Feel free to submit a PR.

**Comment by bonebox** [comment]
Well, not _that_ straightforward ;).  The C functions you were using (`strptime` and `mktime` don't support millisecond precision, so I had to use `NSDateFormatter` instead.  #104

**Comment by 3lvis** [comment]
@bonebox I guess you're right! I went for the C functions because using `NSDateFormatter` is *really* slow compared to doing it with C. Since dates are so common this change could increase the parsing time considerably. 😞

**Comment by 3lvis** [comment]
Also the date parsing code is pretty bad documented. Sorry for that.

**Comment by 3lvis** [comment]
Microsecond support is missing, although that's probably not critical.

https://github.com/hyperoslo/NSManagedObject-HYPPropertyMapper/pull/105

**Comment by bonebox** [comment]
Yeah, I figured that was why you weren't using it. I first tried something like your solution but couldn't get it to work like I wanted. Anyway, thanks for updating it!
