### ISSUE TITLE
NSLog & printf leftovers (in NSDate+HYPPropertyMapper.m)

### ISSUE THREAD

**Issue by alladinian** [hyperoslo/NSManagedObject-HYPPropertyMapper#106]
Hi there,
Just updated and saw a lot of noise caused by `NSLog` and `printf`s in 9db092472833f8b8821a19091509a62bc316d394  ( I suppose they were meant for quick debug but somehow left on the commit).
I guess could go ahead and remove them and do a PR but thought to ask first :)

Thanx,
Vasilis

**Comment by 3lvis** [comment]
Nooo, this should go away, sorry for that.

**Comment by alladinian** [comment]
Fixed on 2245dcc26fb19810c398c3d432b5048c882b4b41

**Comment by 3lvis** [comment]
Great catch, thanks!

https://github.com/hyperoslo/NSManagedObject-HYPPropertyMapper/releases/tag/3.6.2
