### ISSUE TITLE
Crash (indefinite cycle)

### ISSUE THREAD

**Issue by Sorix** [hyperoslo/NSManagedObject-HYPPropertyMapper#112]
HYPPropertyMapper always crashes when I try to add same object to parent object and child relationship has same object inside.

![coredata](https://cloud.githubusercontent.com/assets/5610904/17976058/eb08fa1c-6afc-11e6-89dc-0dd94a016bf4.png)

I've created new example app where you can easily crash HYPPropertyMapper, I think that will be much better to understand.

[Project: hypbug.zip](https://github.com/hyperoslo/NSManagedObject-HYPPropertyMapper/files/437451/hypbug.zip)

**Comment by 3lvis** [comment]
Thanks! I was able to reproduce. I'll check what's going on.

**Comment by 3lvis** [comment]
Not to the point, but your entities should probably be like this, since you can access to the owner of a task through the tasklist.

```swift
task.taskList.owner
```

<img width="257" alt="screen shot 2016-08-26 at 07 22 03" src="https://cloud.githubusercontent.com/assets/1088217/17994995/f379bf9a-6b5d-11e6-94ef-a55040aa5188.png">

**Comment by 3lvis** [comment]
I'm afraid that this is not a bug per se, but that's the intended behavior.

Each entity will print all it's items and related objects, so in reality the result is more like this, generating a recursive result:

```json
{
  "id": 1,
  "owner": {
    "id": 1,
    "task": ...
    "taskList": ...
  },
  "tasks": [
    {
      "id": 1,
      "owner": {
        "id": 1
        "task": ...
        "taskList": ...
      }
    }
  ]
}
```

**Comment by 3lvis** [comment]
I think the current result makes a lot of sense. Do you have any other suggestions on how this could be fixed?

Meanwhile I would suggest to maybe change a bit your model so this recursion doesn't happen. If you want to access the owner from a task it could also be done like this:

```swift
task.taskList.owner
```

<img width="257" alt="screen shot 2016-08-26 at 07 22 03" src="https://cloud.githubusercontent.com/assets/1088217/17994995/f379bf9a-6b5d-11e6-94ef-a55040aa5188.png">

**Comment by Sorix** [comment]
I understand why it is intended result, but that's rather big problem.

1. I can't use task.taskList.owner because task for example may have own owner and may have other owner. As temporary solution I'm using duplicating of `Owner` (with other ID) in my own app, but that's not best solution.
2. That was an example, also I using `Tag` entity for example to tag task and taskList, but I can't do because we will receive indefinite cycle again. You're loosing very important feature of Core Data — using the same object to several entities.
3. It's very easy to accidentally crash application if you're set same object (that may be done by error for example or just… you haven't thought that it may be possible). If that problems occurs user will need to reinstall application in most cases because on every export will get crash (and that export most times is done automatically).

I have my minds about solution.

### The most hard way — automatic.
Detect that object is already being exported somewhere in that method call and export only ID of that object in that case.

```
{
  "id": 1,
  "owner": { # mark in memory that we exported it
    "id": 1,
    "task": "{ contents of the task here, which inside has an owner and a taskList}",
    "taskList": "{ contents of the taskList here, which inside has a list of tasks and an owner}"
  },
  "tasks": [
    {
      "id": 1,
      "owner": { #uh! we have already exported that object, don't export it again
        "id": 1 # just we will make "link" to ID
      }
    }
  ]
}
```

That way will need support from Sync module.

### Simpler way — manual
Grant an ability to mark relationships as "non-exportable" to HYPDictionary in Core Data userInfo. So I can mark at `Owner` and `Tag` both relationships as non-exportable because I know that entities is used only inside other Entities and I won't do standalone export of Owner/Tag entity.

I don't know if you will need to update Sync so it won't destroy Owner/Tag entity if Sync won't see relationships inside JSON (will Sync assume it is nil or it won't touch it?).

`Owner` & `Tag` entities will be filled by Sync from other sources, in my example relationships will be restored when Sync will get `Owner` from `Tasklist` (reverse relationship will be restored automatically by Core Data). And from `Task` it will see ID and restore relationship from `Task` to `Owner` again.

Example result:

```
{
  "id": 1,
  "owner": { # mark in memory that we exported it
    "id": 1,
    "task": "{ contents of the task here, which inside has an owner and a taskList}",
    "taskList": "{ contents of the taskList here, which inside has a list of tasks and an owner}"
  },
  "tasks": [
    {
      "id": 1,
      "owner": {
        "id": 1,
        "name": "example_name",
        # we're prohibitted to export relationships, so just export what we've allowed
      }
    }
  ]
}
```

**Comment by 3lvis** [comment]
Thanks a lot for following up on this. I think the "automatic" way is too magical and makes a few assumptions that might not be correct in most cases. Meanwhile the manual way would handle this pretty well.

Just to confirm, would the simpler way fix your issue 100%, or would just help?

What's your ideal scenario? What time of backend are you using? Is it Rails?

Thanks again for your answers, they are very useful.

**Comment by Sorix** [comment]
Sorry for a long answer time, I've tested a little. Yes if you can add a key to userinfo (like `hyper.ignore = true`) that will prohibit exporting variable or relationship to JSON that will solve my problem. I think it will solve not only my problem, any developer may issue such problem if using more complicated Core Data schemes.

I think anyway it will be good option if you don't want to export some data from Core Data.
