### ISSUE TITLE
Date are not saved to Date type 

### ISSUE THREAD

**Issue by smartjx** [hyperoslo/NSManagedObject-HYPPropertyMapper#114]
I have update my pods to the latest sync version. 
But my time data are not saved to core data using Date type.
My test date format is  UpdateTime=2016-04-22T14:54:36.613.

I'm now changing all my date type in coredata to string. Please let me know if there are any fixes,Thank you.

**Comment by 3lvis** [comment]
https://github.com/3lvis/DateParser/issues/4
