### ISSUE TITLE
Deep mapping + remote key problems

### ISSUE THREAD

**Issue by pgawlowski** [hyperoslo/NSManagedObject-HYPPropertyMapper#148]
Let's assume that I'm using deep mapping

```
{
  "id": 1,
  "name": "John Monad",
  "company": {
    "name": "IKEA"
  }
}
```

so field company got` User.Info `like` hyper.remote_key = company.name`

Now I'm trying to get back dictionary with structure like above. That's why I introduced ValueTransformer

However using 
`let dict = item.hyp_dictionary() `
will return not a company key but company.name key.

My target is to have:
- remote key like company.name
- dictionary with original structure using ValueTransformer for company
- dictionary with original keys - not remote one

**Comment by 3lvis** [comment]
Hi @pgawlowski!

I'm glad you got deep mapping working for filling with JSON. Would be awesome to have reversed deep mapping working so you can have what you're asking for. Sadly is a missing feature, if you feel like working on it I would be glad to assist in our Gitter chat. https://gitter.im/SyncDB/SYNCPropertyMapper

**Comment by pgawlowski** [comment]
@3lvis why not :) SyncDB seems to me as pretty handy solution. Will try to work on it in the meantime.

Got also additional question. While I was trying to fetch entity with relationship, I'm also receiving different key-mapping. 

E.x. for product it's going to be product_attributes. Is it possible to map it back just as "product". What's the purpose of this nested attribute key?

**Comment by 3lvis** [comment]
@pgawlowski we used that to match what Ruby supports, to get normal style JSON you can use

```swift
let result = workout.hyp_dictionary(using: .snakeCase, andRelationshipType: .array)
```

**Comment by pgawlowski** [comment]
@3lvis - ok, remote mapping seems to be ok now. However update problems occurred.
I've got `code` attributed marked as `hyper.isPrimaryKey = true`
I'm fetching entry correctly. Changing quantity value, then I perform:
`Sync.changes` with `.Insert .Update`

The effect is like this:
- original entry loses relationship to `product` object (To-One, delete rule - No Action)
- duplicated entry with same code (primary key), correct relationship and new quantity

I thought primary key is for updating objects + preserving uniqueness of entries.

**Comment by 3lvis** [comment]
@pgawlowski should we close this issue then?
