### ISSUE TITLE
Add support for to-one relationships

### ISSUE THREAD

**Issue by 3lvis** [hyperoslo/NSManagedObject-HYPPropertyMapper#28]
```json
"first_name": "John",
"last_name": "Hyperseed",
"company": {
    "id": 14,
    "name": "Facebook"
}
```

**Comment by NSElvis** [comment]
I opted to fix this on Kipu.

https://github.com/NSElvis/Kipu/blob/master/Source/Kipu.m#L213

**Comment by NSElvis** [comment]
I'll see if we can add this one to property mapper, would make a lot of sense.

**Comment by 3lvis** [comment]
You can easily use Sync for this

https://github.com/hyperoslo/Sync/blob/master/Source/Sync.h#L17
