### ISSUE TITLE
Add mapping for arrays as data

### ISSUE THREAD

**Issue by RamonGilabert** [hyperoslo/NSManagedObject-HYPPropertyMapper#46]
We could add support in three lines of code to store arrays into core data. Sometimes it can make more sense not to have a relation but to store an array, that way just adding the property as NSData could make the work. :)

**Comment by NSElvis** [comment]
One thing that could use this is `tags` they are usually an array of `strings` inside an entity.

They don't need a relationship for that. 

+1 for this feature

**Comment by RamonGilabert** [comment]
I'll implemented today afternoon then! :P

**Comment by kostiakoval** [comment]
We need this functionality in Sync as well in Nokkeltal project

**Comment by zenangst** [comment]
![giphy-25](https://cloud.githubusercontent.com/assets/57446/6820050/44820c6c-d2cb-11e4-8018-74483e8ba089.gif)

**Comment by kostiakoval** [comment]
@zenangst Man, your gifs are amazing. Made my Smile :D

**Comment by RamonGilabert** [comment]
This was fixed in #47! :dancer: :D

**Comment by zenangst** [comment]
@RamonGilabert now you get :cake:

**Comment by NSElvis** [comment]
I think this also allows to support `NSDictionaries`

**Comment by RamonGilabert** [comment]
It does!
