### ISSUE TITLE
Add support for custom mapping in relationships

### ISSUE THREAD

**Issue by 3lvis** [hyperoslo/NSManagedObject-HYPPropertyMapper#52]
At the moment we are only supporting custom mapping for attributes.

The idea is to support relationships too =>https://github.com/hyperoslo/NSManagedObject-HYPPropertyMapper/releases/tag/2.9

**Comment by RamonGilabert** [comment]
I tried something! :o #54

**Comment by 3lvis** [comment]
I wonder if this is a `Sync` related issue more than property mapper.

The idea was that you could have a custom relationship.

In Sync if you send a JSON:
```json
{
  "id":1,
  "name":"User name",
  "notes":[
    {
      "body":"Hi there"
    },
    {
      "body":"Hi there 2"
    }
  ]
}
```

This will map the user notes with the `notes` relationship, but if in the JSON `notes` were called `annotations` then this wouldn't work since the app will try to map to `notes` (the Core Data relationship)

**Comment by 3lvis** [comment]
@kostiakoval Might have a more specific use case. It looks like this should go into Sync
