### ISSUE TITLE
Support date strings without timestamp

### ISSUE THREAD

**Issue by 3lvis** [hyperoslo/NSManagedObject-HYPPropertyMapper#60]
"1990-01-20" should become 20 of January, 1990 at 00:00.

**Comment by zenangst** [comment]
@fespinoza seems correct? Is it the right format?

**Comment by fespinoza** [comment]
exactly `YYYY-MM-DD`

**Comment by kostiakoval** [comment]
what standard is that , ISO?

**Comment by 3lvis** [comment]
Fixed on 3.0.3 https://github.com/hyperoslo/NSManagedObject-HYPPropertyMapper/releases
