### ISSUE TITLE
Crash at app startup (initial sync?)

### ISSUE THREAD

**Issue by attila-at-hyper** [hyperoslo/NSManagedObject-HYPPropertyMapper#65]
Happens 8 of 10 app starts.

2015-04-30 13:33:18.580  beta[35225:2353580] *** Terminating app due to uncaught exception 'NSObjectInaccessibleException', reason: 'CoreData could not fulfill a fault for '0xd000000001580002 x-coredata://BCE5A740-F5EA-4FFE-9126-C0C2C5635821/WeekNumberSet/p86''
*** First throw call stack:
(
0 CoreFoundation 0x000000010d0e0c65 __exceptionPreprocess + 165
1 libobjc.A.dylib 0x000000010cd79bb7 objc_exception_throw + 45
2 CoreData 0x000000010a86d1fd _PFFaultHandlerLookupRow + 1949
3 CoreData 0x000000010a86c659 _PF_FulfillDeferredFault + 265
4 CoreData 0x000000010a86c437 _sharedIMPL_pvfk_core + 103
5 CoreData 0x000000010a89f513 _PF_Handler_Public_GetProperty + 163
6  beta 0x0000000109e822b6 -[NSManagedObject(HYPPropertyMapper) hyp_fillWithDictionary:] + 854
7  beta 0x0000000109e951fa __78+[Sync changes:inEntityNamed:predicate:parent:inContext:dataStack:completion:]_block_invoke57 + 106
8  beta 0x0000000109ddd984 +[DATAFilter changes:inEntityNamed:localKey:remoteKey:context:predicate:inserted:updated:] + 2564
9  beta 0x0000000109e94cfc +[Sync changes:inEntityNamed:predicate:parent:inContext:dataStack:completion:] + 1484
10  beta 0x0000000109e93372 -[NSManagedObject(Sync) sync_processToManyRelationship:usingDictionary:andParent:dataStack:] + 1986
11  beta 0x0000000109e927de -[NSManagedObject(Sync) sync_processRelationshipsUsingDictionary:andParent:dataStack:error:] + 558
12  beta 0x0000000109e95229 __78+[Sync changes:inEntityNamed:predicate:parent:inContext:dataStack:completion:]_block_invoke57 + 153
13  beta 0x0000000109ddd984 +[DATAFilter changes:inEntityNamed:localKey:remoteKey:context:predicate:inserted:updated:] + 2564
14  beta 0x0000000109e94cfc +[Sync changes:inEntityNamed:predicate:parent:inContext:dataStack:completion:] + 1484
15  beta 0x0000000109e93f99 __61+[Sync changes:inEntityNamed:predicate:dataStack:completion:]_block_invoke + 121
16  beta 0x0000000109de0eba __43-[DATAStack performInNewBackgroundContext:]_block_invoke + 58
17 CoreData 0x000000010a897a79 developerSubmittedBlockToNSManagedObjectContextPerform + 201
18 libdispatch.dylib 0x000000010d89e614 _dispatch_client_callout + 8
19 libdispatch.dylib 0x000000010d8856a7 _dispatch_queue_drain + 2176
20 libdispatch.dylib 0x000000010d884cc0 _dispatch_queue_invoke + 235
21 libdispatch.dylib 0x000000010d8883b9 _dispatch_root_queue_drain + 1359
22 libdispatch.dylib 0x000000010d889b17 _dispatch_worker_thread3 + 111
23 libsystem_pthread.dylib 0x000000010dc0b637 _pthread_wqthread + 729
24 libsystem_pthread.dylib 0x000000010dc0940d start_wqthread + 13
)
libc++abi.dylib: terminating with uncaught exception of type _NSCoreDataException

**Comment by 3lvis** [comment]
This is usually related to the method been called more than once. So the object gets removed from one thread and accessed from other one. 

Can you make sure you're calling the method once?

**Comment by 3lvis** [comment]
Please make sure to not call the method while other one is in progress. Let me know if this didn't fixed your issue and I will reopen this.

:dancers:
