### ISSUE TITLE
Support IS8601 strings with milliseconds and timezone

### ISSUE THREAD

**Issue by sononum** [hyperoslo/NSManagedObject-HYPPropertyMapper#68]
the iso8601 parser is not able to parse an iso8601 string that contains milliseconds and timezone, e.g. "2015-06-23T12:40:08.594+02:00"

**Comment by 3lvis** [comment]
@sononum This is great, Ulrich! Would you mind sending a PR including some additional test cases?

**Comment by 3lvis** [comment]
@sononum nevermind, just saw your PR :clap:
