### ISSUE TITLE
Support for custom date formatter

### ISSUE THREAD

**Issue by 3lvis** [hyperoslo/NSManagedObject-HYPPropertyMapper#71]
From time to time there will be the need for a person to use a custom date formatting. This could be added using an additional key adding the expected format.

```
hyper.formatDate: YYYY-MM-DD
```

**Comment by jeffleeismyhero** [comment]
🆙

**Comment by 3lvis** [comment]
Thanks to #102 this should be possible now with some additional work. It needs some documentation in the README, though.
