### ISSUE TITLE
hyp_dictionary doesn't parse NSDate properties to Strings

### ISSUE THREAD

**Issue by nbarnold01** [hyperoslo/NSManagedObject-HYPPropertyMapper#72]
I'm trying to use the `hype_dictionary` method to basically do the opposite of `hyp_fillWithDictionary`. It works well until it gets to `NSDate` objects, in which case it keeps the NSDate as an NSDate. That's not bad per-say, but it's a little inconvenient for me to have to changed those properties that are NSDates into formatted strings after they've been converted to the fields that the server is expecting.

`NSJSONSerialization` chokes on `NSDates`. Is this worthy of a pull request?

**Comment by nbarnold01** [comment]
Perhaps this is related to #71.

**Comment by 3lvis** [comment]
@nbarnold01 Hi Nathan, we were using that method to send it to the backend as a POST body. We were using AFNetworking and we didn't had this problem. Converting NSDate's when constructing the `hyp_dictionary` would be a nice feature, please go for it :wink: 

Could you tell me what's your use case for this stringified NSDates?

**Comment by nbarnold01** [comment]
I'm working on a todo list as a side project and one of the requirements is a fairly robust offline mode. Two important fields for tasks are "completed_on" and "due_date". I'm using AFNetworking as well and I looked into how AFNetworking serializes NSDate into JSON. Mattt said that it's [outside AFNetworking's area of responsibility.](https://github.com/AFNetworking/AFNetworking/issues/2377)

**Comment by 3lvis** [comment]
@nbarnold01 do it!

**Comment by 3lvis** [comment]
Fixed on #73
