### ISSUE TITLE
Support camelCase 

### ISSUE THREAD

**Issue by 3lvis** [hyperoslo/NSManagedObject-HYPPropertyMapper#86]
Twitter:
`"created_at": Thu Nov 03 05:19;38 +0000 2011"`

Bing:
`"DateTime": "2011-10-29T09:35:00Z"`

Foursquare:
`"createdAt": 1320296464`

http://apigee.com/about/blog/technology/restful-api-design-what-about-attribute-names

**Comment by justinmakaila** [comment]
You could definitely solve this in Swift by using a protocol, and having developers override a `func customRemoteString() -> String` or something of the like, and provide a default implementation for `hyp_remoteString` to invoke `customRemoteString`

**Comment by 3lvis** [comment]
Hi @justinmakaila,

Are you facing the same issue? What kind of library/framework are you using for your backend?

**Comment by justinmakaila** [comment]
Hey,

I've actually rewritten most of this library, as well as Sync, in Swift to take advantage of the language features.

Our backend is a GraphQL implementation with camel cased property names.

I didn't want to use this implementation because it's opinionated as to what remote property names should look like, and it didn't provide a Carthage implementation ;)

Justin Makaila

Sent from
https://polymail.io/

On Wed, Mar 09, 2016 at 18:57 "Elvis Nuñez"

<
mailto:
> wrote:

Hi
https://github.com/justinmakaila
,

Are you facing the same issue? What kind of library/framework are you using for your backend?

**Comment by 3lvis** [comment]
Hahah, good to now! We'll hopefully do the transition to Swift soon, and move over to also supporting camelCase, this days I'm working with MongoDB backed backends and getting camelCase support is important.

**Comment by 3lvis** [comment]
Fixed by the fantastic @wainglaister 👏  Released on 3.5.0

https://github.com/hyperoslo/NSManagedObject-HYPPropertyMapper/releases/tag/3.5.0

**Comment by achirkof** [comment]
Hi!
I see that `camelCase` is supported but can't realise how to use it. By default I get `snake_case` result doing 
```swift
let entityJSON = myEntity.hyp_dictionary()
print(entityJSON)
```
My Core Data entity names are `camelCase`. 
I also have MongoDB backend and data model described by `camelCase` names.

**Comment by 3lvis** [comment]
Hi @achirkof,

At the moment camelCase is supported for `hyp_fill` not to generate the dictionary.

**Comment by 3lvis** [comment]
Sounds like a very useful feature, though. I would go for:

```swift
let entityJSON = myEntity.hyp_dictionary(type: .camelCasee)
let entityJSON = myEntity.hyp_dictionary(type: .snakeCase)
```

Feel free to submit a PR :)

**Comment by achirkof** [comment]
It's written on Objective-C, but I'm writing only Swift now. Even read Obj-c code is hard to me. Sorry :(

**Comment by 3lvis** [comment]
No problem :)

**Comment by 3lvis** [comment]
I'll try to take a look as soon as I have some time.

**Comment by achirkof** [comment]
And one more comment about converting to JSON. Result JSON is not valid. Now I'm trying to find all mistakes.
Here the list:

- each JSON line finished by `;` but should `,`
- key-value couples writes in format `"key" = "value"` but should `"key": "value"`. For example `"_id" = DGzSEUYfl02nUwKQr;` but should be `"_id": DGzSEUYfl02nUwKQr,` and it true only for related objects
- each member of array enumerates like `0 =      `
```json
"exercise_sets_attributes" =      
			   			{
							0 = 	
								{
									"_id" = DGzSEUYfl02nUwKQr;
									"is_completed" = 1;
									"set_number" = 0;
									"set_reps" = 8;
									"set_weight" = "2.5";
								};
						};
```
- some values are not wrapped `""`

Below are incorrect and correct JSON to compare.
**Incorrect**
```json
Optional([
"_id": TvBHSrLWYEn84cuyA, 
"workout_desc": <p>Test program</p>, 
"workout_name": Test 1, 
"workout_exercises_attributes": 
	{
		0 =     {
					"_id" = nfjSgCkCxa533hxiB;
					"exercise_desc" = "";
					"exercise_name" = "";
					"exercise_sets_attributes" =      
			   			{
							0 = 	
								{
									"_id" = DGzSEUYfl02nUwKQr;
									"is_completed" = 1;
									"set_number" = 0;
									"set_reps" = 8;
									"set_weight" = "2.5";
								};
						};
					"main_muscle" = "";
				};
		1 =     {
					"_id" = 63wNcGjeJyA5AAHaN;
					"exercise_desc" = "";
					"exercise_name" = "";
					"exercise_sets_attributes" =     
						{
						};
					"main_muscle" = "";
				};
		2 =     {
					"_id" = drg4TciKLLFtrJbCX;
					"exercise_desc" = "";
					"exercise_name" = "";
					"exercise_sets_attributes" =      
					   {
							0 =           
								  {
									"_id" = CrClrjXP4KYxszdJ3;
									"is_completed" = 1;
									"set_number" = 0;
									"set_reps" = 8;
									"set_weight" = "2.5";
								};
						};
					"main_muscle" = "";
				};
	}
])

```

**Correct**
```json
{
  "workout": [
    {
      "_id": "TvBHSrLWYEn84cuyA", 
      "workout_desc": "<p>Test program</p>", 
      "workout_exercises_attributes": [
        {
          "_id": "nfjSgCkCxa533hxiB", 
          "exercise_desc": "some desc", 
          "exercise_name": "name", 
          "exercise_sets_attributes": [
            {
              "_id": "DGzSEUYfl02nUwKQr", 
              "is_completed": 1, 
              "set_number": 0, 
              "set_reps": 8, 
              "set_weight": "2.5"
            }
          ], 
          "main_muscle": "muscle"
        }, 
        {
          "_id": "63wNcGjeJyA5AAHaN", 
          "exercise_desc": "ex desc", 
          "exercise_name": "ex name", 
          "exercise_sets_attributes": [], 
          "main_muscle": ""
        }, 
        {
          "_id": "drg4TciKLLFtrJbCX", 
          "exercise_desc": "ex desc", 
          "exercise_name": "ex name", 
          "exercise_sets_attributes": [
            {
              "_id": "CrClrjXP4KYxszdJ3", 
              "is_completed": 1, 
              "set_number": 0, 
              "set_reps": 8, 
              "set_weight": "2.5"
            }
          ], 
          "main_muscle": "muscle"
        }
      ], 
      "workout_name": "Test 1"
    }
  ]}

```
I'm happy to help if I can, not in code but in testing for example.

**Comment by 3lvis** [comment]
@achirkof I believe the JSON is correct, you're just using the wrong way of print it.

To visualize exported JSON don't use `print(json)`. Instead use the pretty print version.

```swift
print(String(data: try! JSONSerialization.data(withJSONObject: JSON!, options: .prettyPrinted), encoding: .utf8)!)
```

**Comment by 3lvis** [comment]
Also use this version instead, the default one adds the `_attributes` part, which is optimized for Ruby on Rails. 

```swift
let json = taskList.hyp_dictionary(using: .array)
```

**Comment by 3lvis** [comment]
You can find more on the README.

https://github.com/SyncDB/SYNCPropertyMapper#relationships

**Comment by achirkof** [comment]
Oh.. yes. I'm sorry for wasting your time. Everything is correct if use use your advices. Thank you very much!

**Comment by achirkof** [comment]
Hi @3lvis ! 
Did you find solution how to use `camelCase` for exporting core data model to JSON? I checked a lot of other solutions which provide similar functionality, but did'n find better then SYNCPropertyMapper.

**Comment by 3lvis** [comment]
@achirkof Made an issue for it. I'll give later, should be straightforward.

https://github.com/SyncDB/SYNCPropertyMapper/issues/137

**Comment by 3lvis** [comment]
Done! 💥

**Comment by achirkof** [comment]
Awesome!!! :tada: 
Thank you!
