### ISSUE TITLE
ToMany relationship can be NSOrderedSet

### ISSUE THREAD

**Issue by iroller** [hyperoslo/NSManagedObject-HYPPropertyMapper#94]
When checking for type of relationship it should check for both NSOrderedSet and NSSet. Otherwise ordered NSSets are being treated as ToOne relation and failing.

https://github.com/hyperoslo/NSManagedObject-HYPPropertyMapper/blob/master/Source/NSManagedObject%2BHYPPropertyMapper.m#L81

**Comment by 3lvis** [comment]
Good one. :)

**Comment by 3lvis** [comment]
@iroller Btw, what's your use case for ordered relationships? I've never had to use them because most of the time I do the sorting using NSFetchedResultsController + NSSortDescriptors.

**Comment by iroller** [comment]
It's a new app and that's the first time I'm using NSOrderedSet for some of the relationships. It's supposed to let me not to create and manage "internalOrder" for each item I need. But I didn't make use of it yet, working on things with higher priorities atm.
