### ISSUE TITLE
NSDecimalNumber support

### ISSUE THREAD

**Issue by wh33ler** [hyperoslo/NSManagedObject-HYPPropertyMapper#96]
Am I just overlooking something or does this Library not support NSDecimalNumber as Core Data Attribute Class? I would appreciate the support for this if it does not currently.

**Comment by wh33ler** [comment]
#97 I fixed my issue with this pull request.

**Comment by 3lvis** [comment]
Fixed on https://github.com/hyperoslo/NSManagedObject-HYPPropertyMapper/pull/98

Thanks :beers:

**Comment by 3lvis** [comment]
Btw, the `hyp_dictionary` version returns a NSDecimalNumber instead of a NSString to be consistent with what happens with integers and floats.
